export const SET_BUCKETS = "[DASHBOARD] SET_BUCKETS";
export const SET_FOCUS_BUCKET = "[DASHBOARD] SET_FOCUS_BUCKET";
export const SET_FOCUS_STOCK = "[DASHBOARD] SET_FOCUS_STOCK";
export const SET_MODE = "[DASHBOARD] SET_MODE";
export const SET_BUCKET_GRAPH = "[DASHBOARD] SET_BUCKET_GRAPH";
export const SET_STOCK_GRAPH = "[DASHBOARD] SET_STOCK_GRAPH";
